### ISSUE TITLE
More spoofing vessels on 2015

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/vessel-lists#12]
@davidkroodsma below some examples of MMSI that are spoofing that are not present on the latest version of you spoofing list.

* `412371206` 

<img width="716" alt="hu_yu_927" src="https://cloud.githubusercontent.com/assets/355597/15048032/fcd1ab28-12bd-11e6-9c52-7b884036e31d.png">

* `412420875`

<img width="683" alt="412420875" src="https://cloud.githubusercontent.com/assets/16544587/15048217/8d990082-12b6-11e6-9c51-09fb010368c2.png">

* `432453000`

<img width="478" alt="432453000" src="https://cloud.githubusercontent.com/assets/16544587/15048336/2513208c-12b7-11e6-8487-08380ad39733.png">

* `204848000`

<img width="134" alt="204848000" src="https://cloud.githubusercontent.com/assets/16544587/15048489/c8d3904e-12b7-11e6-91c2-1e7a75b9eb26.png">

* `412439587`

<img width="717" alt="412439587" src="https://cloud.githubusercontent.com/assets/16544587/15048751/ccd7fbd4-12b8-11e6-8c08-64cfa2244e76.png">

* `412420787`

<img width="625" alt="412420787" src="https://cloud.githubusercontent.com/assets/16544587/15048987/fcc9414e-12b9-11e6-84bc-d342021ddfce.png">

* `412698980`

<img width="530" alt="412698980" src="https://cloud.githubusercontent.com/assets/16544587/15049359/ed9c4e12-12bb-11e6-91b5-b38e991cc9f8.png">

* `503005660`

<img width="241" alt="503005660" src="https://cloud.githubusercontent.com/assets/16544587/15049463/71817aa4-12bc-11e6-88ea-2bd0a95c9105.png">

* `251839540`

<img width="338" alt="251839540" src="https://cloud.githubusercontent.com/assets/16544587/15050347/4485ff48-12c1-11e6-8a2e-c65ca2f38d06.png">

* `251452000`

<img width="522" alt="251452000" src="https://cloud.githubusercontent.com/assets/16544587/15050530/6abe30a8-12c2-11e6-9b93-1e9091dd1e25.png">

* `412205512`

<img width="113" alt="412205512" src="https://cloud.githubusercontent.com/assets/16544587/15056335/07b75e18-12df-11e6-93d7-c425d8ae6def.png">

* `224070150`

<img width="84" alt="224070150" src="https://cloud.githubusercontent.com/assets/16544587/15056848/c9de13f4-12e1-11e6-96c2-cd5e844adc5a.png">

* `247150050`

<img width="240" alt="247150050" src="https://cloud.githubusercontent.com/assets/16544587/15057054/ed000238-12e2-11e6-8fb7-c2f90860ff91.png">

* `242131100`

<img width="205" alt="242131100" src="https://cloud.githubusercontent.com/assets/16544587/15057230/ccfe0650-12e3-11e6-8f9c-0aee1349cce4.png">

* `416132500`

<img width="248" alt="416132500" src="https://cloud.githubusercontent.com/assets/16544587/15057526/34eb6d4c-12e5-11e6-857c-df5adde599ba.png">

* `440933000`
<img width="763" alt="440933000" src="https://cloud.githubusercontent.com/assets/16544587/15057885/1d8fda32-12e7-11e6-9be3-0c7fc968d0ae.png">

* `258139000`

<img width="387" alt="258139000" src="https://cloud.githubusercontent.com/assets/16544587/15057962/8ed64ae6-12e7-11e6-9fdf-732a11ef0af7.png">

**Comment by geowurster** [comment]
Migrated to `treniformis`.
