### ISSUE TITLE
Organize vessel-list repo

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/vessel-lists#19]
We need to make a well documented structure for the vessel-list repo. We want to modify the `README.md` so it is clear what is present on each directory. Also give guidance of which information is needed on each commit message and metadata of the files.

Also we need to clean up all the unnecessary stuff that is now present on the repo.

* [ ] Design a good structure for the directory structure.
  * [ ] Installable.
  * [ ] Basic API to get at common files.
* [ ] Update README.
  * [ ] Include the directory design.
  * [ ] mention the tagging procedure.
* [ ] If some files need to be cleaned create tickets for the authors of the files with instruction to clean/delete.

**Comment by bitsofbits** [comment]
Thoughts on API:

- __init__.py pulls the various files into dicts indexed by year.
     * makes sense for spoofing and likely fishing maybe not other stuff
     * something similar probably works for classification_results
- classification lists probably not accessible through API, just go grab them directly.

Other Stuff:

Should the code to create the combined classification list be moved here from the NN repo?

**Comment by geowurster** [comment]
Handled by https://github.com/GlobalFishingWatch/treniformis/pull/1.
