### ISSUE TITLE
Define Github release tagging process

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/vessel-lists#25]
Define the procedure for creating tagged releases that are pip-installable.  Maybe put it in a readme and give it to @bitsofbits to execute.

**Comment by bitsofbits** [comment]
@geowurster, on the pip installable front I was thinking of moving everything that needs installing into a vessel_lists subdirectory to make creating the `setup.py` file easy.  Then adding an `__init__.py` file that pulled in the lists that we want to expose and stashing them in dictionary's keyed by year (or whatever is appropriate for that list). So , after installation, one should be able to do something like:
```
import vessel_lists
lf2015 = vessel_lists.likely_fishing[2015]
# Do something with lf2015....
```

Thoughts?

**Comment by geowurster** [comment]
@bitsofbits Yeah something like that.  The MVP is to provide easy hooks to get at the files on disk, but we need to be a little careful with the API so we don't end up in a deprecation nightmare.  We could provide some intelligent I/O and data structures at a later date using ourselves as the first customer.

We need a better name for the package though.

**Comment by bitsofbits** [comment]
@geowurster What's the guiding principle for names? Greek? Old? There's
`Metis` who was a Greek Goddess of Wisdom who was also (probably) a sea
nymph (or at least was one of the Oceanids).  Other than that I've got
nothing at the moment. I typically just give things boring names....

**Comment by geowurster** [comment]
@bitsofbits I'm bad at naming projects too but most of the GFW stuff is marine themed, so the `pelagos-client` is named after the [pelagic zone](https://en.wikipedia.org/wiki/Pelagic_zone), the `benthos-pipeline` is named after the [benthic zone](https://en.wikipedia.org/wiki/Benthic_zone), `pleuston` is a [kind of organism](https://en.wikipedia.org/wiki/Pleuston) that lives in the air-water boundary of the water.

If we can't think of anything else we could go with `gfw-vessel-lists` so its at least a bit more branded.

**Comment by geowurster** [comment]
@bitsofbits Have you managed a project on PyPi before?

**Comment by bitsofbits** [comment]
@geowurster , nope. So I'll need some hand holding.

**Comment by bitsofbits** [comment]
@geowurster,  Would `plueston`, or something similar be `pleuston-vessel-lists`, `pleuston-lists`, `plueston-vessels` or something?  Plueston, by itself seems like a nice, word, but most of the combinations seem unwieldy, although the last one isn't bad.   I'm kind of partial to `gfw-vessel-lists` though.

Mussidae (Brain coral) seems like a good name for the NN vessel classifier project though.

**Comment by geowurster** [comment]
@bitsofbits No I mean we already have a pleuston but its private.  What does a pleuston eat?

I like Mussidae for the NN project.

**Comment by geowurster** [comment]
Oh cyanobacteria is a kind of pleuston!  They're pretty cool.

**Comment by geowurster** [comment]
@bitsofbits We need a clear directory structure for this too.  After going through the `dal` install process i think its probably best if the lists live in a sub directory inside the module in `git`.  That would prevent us from having to manage copying the files around in `setup.py`.  Thoughts?  We may be able to incorporate `pkg_resources` somehow for managing the data.

**Comment by bitsofbits** [comment]
@geowurster , that was my thought as well. Just move everything into `gfw_vessel_lists/` or whatever name we are going to install under.

**Comment by geowurster** [comment]
Migrated to `treniformis`.
