### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by geowurster** [GlobalFishingWatch/vessel-lists#26]
`vessel-lists` is boring and non-descript.  Can we come up with something better?  Maybe more fishy?

**Comment by bitsofbits** [comment]
@geowurster : what do think of *turbinaria*? [*Turbinaria reniformis*](https://en.wikipedia.org/wiki/Turbinaria_reniformis) is yellow scroll coral. And what goes on scrolls? Lists!

**Comment by geowurster** [comment]
Oh yeah pretty good!   Looks like [Turbinaria reniformis](https://en.wikipedia.org/wiki/Turbinaria_reniformis) is the only actual scroll coral in that genus, so we could use `turbinaria` or `reniformis`?  Both are arbitrarily hard to remember and not great names, but they work.

**Comment by ezys** [comment]
Nice. If you want a simpler name could be something related to _Alexandria_.  Galen wrote that the Ancient Library of Alexandria (Egypt) was populated in part by compelling any ship that visited the port to surrender their books for immediate copying. Ships, lists, seems appropriate...

**Comment by bitsofbits** [comment]
@geowurster , I think a biologist might go with *t_reniformis* (from *t. reniformis*, which I think is the standard abbreviation), but *t_reniformis* is even worse then *reniformis* as far as being hard to remember and looks bad.  *treniformis*? That's getting

@ezys: I'd be fine with *Alexandria* , although that might be a common name and we might clash with something, so we'd have to check that.

**Comment by geowurster** [comment]
@bitsofbits `alexandria` is (expectedly) already taken on PyPi, so that's a no go.  I think @ezys was mostly suggesting a new domain from which we can look for names.

**Comment by bitsofbits** [comment]
@geowurster : `treniformis`s growing on me a bit since if you Google it you do get the correct organism. `t.reniformis` is even better from a Google perspective but impractical from a packaging perspective.

**Comment by geowurster** [comment]
@bitsofbits Yeah now that I look at it again I kinda like it.

**Comment by geowurster** [comment]
We went with [`treniformis`](https://github.com/GlobalFishingWatch/treniformis).
